name: beamcottagearchitect
favicon: null
layout_spectrum: 0.40724
typography_spectrum: 0.85004
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fcf6a9'
    - '#8b896b'
    - '#4c4c3d'
    - '#1b1c13'
    - '#d5cea0'
  brandStrength: 0.75
  lightness: 0.43098089611157775
  saturation: 0.5558165416587144
  rhythmicContrast: 0.21766655356623232
purpose: []
